version: '2'

services:
  geokrety-mole-name:
    build: .
    image: geokrety-mole-name:1.0.0
    # ports:
    #  - 8000:8000
    volumes:
    #   - .:/opt/flask
      - ./database:/opt/flask/database
      - ./config:/opt/flask/config
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:molename.geokrety.org,molename.gk.kumy.org"
      - "traefik.docker.network=srv_geokrety-front"
    networks:
      - front

networks:
  front:
    external:
      name: srv_geokrety-front
